"""initial_schema

Revision ID: 4205eac6aabb
Revises: 
Create Date: 2026-06-06 23:38:51.052256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '4205eac6aabb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_ticker'), 'source_documents', ['ticker'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", ), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_chunk_id'), 'message_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    
    # Enable Row-Level Security (RLS)
    op.execute("ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE message_citations ENABLE ROW LEVEL SECURITY;")

    # RLS Policies: Profiles
    op.execute(
        "CREATE POLICY select_own_profile ON profiles "
        "FOR SELECT USING (auth.uid() = id);"
    )
    op.execute(
        "CREATE POLICY update_own_profile ON profiles "
        "FOR UPDATE USING (auth.uid() = id);"
    )

    # RLS Policies: Chat Threads
    op.execute(
        "CREATE POLICY select_own_threads ON chat_threads "
        "FOR SELECT USING (auth.uid() = user_id);"
    )
    op.execute(
        "CREATE POLICY insert_own_threads ON chat_threads "
        "FOR INSERT WITH CHECK (auth.uid() = user_id);"
    )
    op.execute(
        "CREATE POLICY update_own_threads ON chat_threads "
        "FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);"
    )
    op.execute(
        "CREATE POLICY delete_own_threads ON chat_threads "
        "FOR DELETE USING (auth.uid() = user_id);"
    )

    # RLS Policies: Chat Messages
    op.execute(
        "CREATE POLICY select_own_messages ON chat_messages "
        "FOR SELECT USING ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_threads "
        "    WHERE chat_threads.id = chat_messages.thread_id AND chat_threads.user_id = auth.uid()"
        "  )"
        ");"
    )
    op.execute(
        "CREATE POLICY insert_own_messages ON chat_messages "
        "FOR INSERT WITH CHECK ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_threads "
        "    WHERE chat_threads.id = chat_messages.thread_id AND chat_threads.user_id = auth.uid()"
        "  )"
        ");"
    )

    # RLS Policies: Message Citations
    op.execute(
        "CREATE POLICY select_own_citations ON message_citations "
        "FOR SELECT USING ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_messages "
        "    JOIN chat_threads ON chat_threads.id = chat_messages.thread_id "
        "    WHERE chat_messages.id = message_citations.message_id AND chat_threads.user_id = auth.uid()"
        "  )"
        ");"
    )
    op.execute(
        "CREATE POLICY insert_own_citations ON message_citations "
        "FOR INSERT WITH CHECK ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_messages "
        "    JOIN chat_threads ON chat_threads.id = chat_messages.thread_id "
        "    WHERE chat_messages.id = message_citations.message_id AND chat_threads.user_id = auth.uid()"
        "  )"
        ");"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RLS Policies
    op.execute("DROP POLICY IF EXISTS select_own_citations ON message_citations;")
    op.execute("DROP POLICY IF EXISTS insert_own_citations ON message_citations;")
    op.execute("DROP POLICY IF EXISTS select_own_messages ON chat_messages;")
    op.execute("DROP POLICY IF EXISTS insert_own_messages ON chat_messages;")
    op.execute("DROP POLICY IF EXISTS select_own_threads ON chat_threads;")
    op.execute("DROP POLICY IF EXISTS insert_own_threads ON chat_threads;")
    op.execute("DROP POLICY IF EXISTS update_own_threads ON chat_threads;")
    op.execute("DROP POLICY IF EXISTS delete_own_threads ON chat_threads;")
    op.execute("DROP POLICY IF EXISTS select_own_profile ON profiles;")
    op.execute("DROP POLICY IF EXISTS update_own_profile ON profiles;")

    # Disable RLS
    op.execute("ALTER TABLE message_citations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_messages DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_threads DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_chunk_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_source_documents_ticker'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('profiles')
    # ### end Alembic commands ###
